### PR TITLE
Feat/pie chart

### LINKED ISSUE #14: Add pie chart for categories screen
Image

interaction should be like this. at the top, please copy the month selection thing from transactions screen. 
we should be able to shift through the month one by one and check the stats.

### PR DESCRIPTION
**Pull request by Rohithgilla12**
Closes #14 

image

### CODE REVIEW

**Review by OjasKarmarkar — CHANGES_REQUESTED** [review]
Can we improve the design a bit , and fix merge conflicts once?

**Review by nullhandler — COMMENTED** [review]
please fetch with sql queries. need to add amount and tick mark selection like shown in the screenshot.

**Comment by nullhandler** [comment]
let me know if you are busy. will add it myself.

**Comment by Rohithgilla12** [comment]
@nullhandler Sorry, had an unplanned travel :(

**Pull request closed without merging**
